// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASBGKY_eHSIZKD6VsTJhzYgUgzcG7iBi4',
    appId: '1:48243820002:android:c2b24b58ff7c7978f325bb',
    messagingSenderId: '48243820002',
    projectId: 'udemy-course-c15f0',
    storageBucket: 'udemy-course-c15f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLTvEG1huNTbHG0LO3X4rVunhTPGCKT_Y',
    appId: '1:48243820002:ios:ee78a69953f783f5f325bb',
    messagingSenderId: '48243820002',
    projectId: 'udemy-course-c15f0',
    storageBucket: 'udemy-course-c15f0.appspot.com',
    androidClientId: '48243820002-oqgii7co2c6jh0uudjacl86sbqvjdlr1.apps.googleusercontent.com',
    iosClientId: '48243820002-lneqqikp5u81nfoqo24ttj37lihsiiqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );
}
